### ISSUE TITLE
Navbar shows dropdown when on mobile in landscape mode.

### ISSUE THREAD

**Issue by cadennabors** [michael-andreuzza/astrosaas#2]
![image](https://github.com/michael-andreuzza/astrosaas/assets/78510667/d7b05508-2682-42cb-b54e-6253d8848d60)

This occurs with mobile resolution while in landscape mode. Pressing the button only changes the icon to an x.

**Comment by michael-andreuzza** [comment]
Thank you, will fix!

**Comment by michael-andreuzza** [comment]
Issue is fixed, thank you for the heads up!
